################################################################################
# Copyright 2017 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 2.0.0
# Author: "barzilay" <barzilay@spritecloud.com>
require 'lapis_lazuli'
require 'lapis_lazuli/cucumber'
require 'chronic'

LapisLazuli::WorldModule::Config.config_file = "config/config.yml"
World(LapisLazuli)

